import { IProduct } from "../types";


export const dummyProducts :IProduct[] = [
  {
    _id: 'prod_001',
    name: 'Classic Cheeseburger',
    description: 'Juicy beef patty with melted cheddar, crisp lettuce, and fresh tomato on a toasted bun.',
    image: '/plainfries.jpg',
    price: 7.99,
    category: 'food',
  },
  {
    _id: 'prod_002',
    name: 'Margherita Pizza (12")',
    description: 'Thin‑crust pizza topped with San Marzano tomato sauce, fresh mozzarella, and basil.',
    image: '/images/margherita_pizza.jpg',
    price: 11.5,
    category: 'food',
  },
  {
    _id: 'prod_003',
    name: 'Chicken Caesar Wrap',
    description: 'Grilled chicken breast, romaine, Parmesan, and Caesar dressing in a soft tortilla.',
    image: '/images/caesar_wrap.jpg',
    price: 6.75,
    category: 'food',
  },
  {
    _id: 'prod_004',
    name: 'Spaghetti Bolognese',
    description: 'Slow‑simmered beef ragu served over al dente spaghetti with Parmesan.',
    image: '/images/spaghetti_bolognese.jpg',
    price: 9.25,
    category: 'food',
  },
  {
    _id: 'prod_005',
    name: 'Still Water (500 ml)',
    description: 'Pure spring water bottled at the source—perfectly balanced minerals.',
    image: '/images/still_water_500.jpg',
    price: 1.2,
    category: 'water',
  },
  {
    _id: 'prod_006',
    name: 'Sparkling Water (330 ml)',
    description: 'Lightly carbonated mineral water for a refreshing fizz.',
    image: '/images/sparkling_water_330.jpg',
    price: 1.5,
    category: 'water',
  },
  {
    _id: 'prod_007',
    name: 'Flavored Water – Lemon & Mint (750 ml)',
    description: 'Naturally infused with zesty lemon and cool mint, no added sugar.',
    image: '/images/lemon_mint_water.jpg',
    price: 2.0,
    category: 'water',
  },
  {
    _id: 'prod_008',
    name: 'Chocolate Fudge Cake Slice',
    description: 'Rich, moist chocolate cake layered with silky fudge frosting.',
    image: '/images/chocolate_fudge_cake.jpg',
    price: 3.75,
    category: 'cakes',
  },
  {
    _id: 'prod_009',
    name: 'Vanilla Bean Cupcake',
    description: 'Fluffy vanilla sponge topped with creamy vanilla‑bean buttercream.',
    image: '/images/vanilla_cupcake.jpg',
    price: 2.25,
    category: 'cakes',
  },
  {
    _id: 'prod_010',
    name: 'Red Velvet Mini Cake',
    description: 'Mini red velvet cake with cream‑cheese frosting and a hint of cocoa.',
    image: '/images/red_velvet_mini.jpg',
    price: 4.0,
    category: 'cakes',
  },
];
